### ISSUE TITLE
[vite] The "attributes" property of ModuleInfo is not supported.

### ISSUE THREAD

**Issue by vdegenne** [justinfagnani/rollup-plugin-css-modules#2]
Using the plugin in Vite gives this error :

```
[vite] Internal server error: [vite] The "attributes" property of ModuleInfo is not supported.
```

Line of interest: https://github.com/justinfagnani/rollup-plugin-css-modules/blob/614a3aa677f641b614058b2672848b4368c78d09/src/index.ts#L18

Output of `this.getModuleInfo(id)` when running this line:
```
{
  id: '/home/xxx/gits/test/node_modules/vite/dist/client/client.mjs',
  meta: {}
}
```

### Versions

vite/5.0.10
linux-x64
node-v20.10.0

**Comment by vdegenne** [comment]
Also something to consider when building a Vite plugin : https://vitejs.dev/guide/api-plugin#plugin-ordering
Since Vite transforms CSS files (`postcss`, ...) it might be wise to use `enforce: 'post'` in this context.

**Comment by justinfagnani** [comment]
This is a Vite issue. It should support import attributes.
